server:
    port: 0

spring:
  application:
    name: user-service


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
#  #    prefer-ip-address: true
##    ip-address: ${server.address}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8001
#    fetch-registry: true
#    register-with-eureka: true


